### ISSUE TITLE
[Bug] "Error: b2 failed to upload" in an endless job that fills the disk

### ISSUE THREAD

**Issue by alx359** [hestiacp/hestiacp#2483]
### Describe the bug

- When uploading to B2 with arguably correct (?) credentials, and `Local backup = No`, the backup script enters in a loop and seemingly never finishes. 
- The `/backup` folder keeps getting filled with `tmp` folders like `tmp.zx3w54G8nb` until eating all free space (not much but enough), and finally aborting with a `not enough diskspace available to perform the backup` email repeating every 5 min.
- In `/var/log/hestia/backup.log`, the only entries about an issue are the repeating summary lines at the end of each backup attempt: `Error: b2 failed to upload user.2022-03-14_08-20-23.tar`.
*
 With `Local backup = Yes` things are better.
- `tar` archives for each user are created successfully and the `tmp` folders cleaned up, as expected
-  `tar` archives are not uploaded to B2, but now there's a quite more meaningful error in the `backup.log` about some cryptic issue with the B2 keys.
*
I'd expect the `Local backup = No` to work the same as `Local backup = Yes` but delete the `tar` files upon upload to B2. 

### Tell us how to replicate the bug

1. Configure > backups >  Local backup = `no`
2. Remote backup = `checked`
3. Protocol: `Backblaze`
4. Bucket: `my-working-bucket-name`
5. Application ID: `<keyID>` from an individually created Application key
6. Application Key: `<applicationKey>` from said Application key
7. 

### Which components are affected by this bug?

Control Panel Backend

### Hestia Control Panel Version

1.5.10

### Operating system

Ubuntu 20.04

### Log capture

```shell
-- SYSTEM --
2022-03-14 08:30:07 user.conf
2022-03-14 08:30:07 stats.log
2022-03-14 08:30:07 history.log
2022-03-14 08:30:07 backup-excludes.conf
2022-03-14 08:30:07 pam

-- WEB --
2022-03-14 08:30:07 domain.org
2022-03-14 08:30:08 domain.net
2022-03-14 08:30:09 dev.domain.com
2022-03-14 08:30:09 excluding directory public_html/wp-content/uploads
2022-03-14 08:30:09 excluding directory public_html/wp-content/cache
2022-03-14 08:30:09 excluding directory public_html/wp-content/wp-cloudflare-super-page-cache
2022-03-14 08:30:09 excluding directory public_html/wp-content/updraft
2022-03-14 08:30:15 domain.com
2022-03-14 08:30:15 excluding directory public_html/wp-content/uploads
2022-03-14 08:30:15 excluding directory public_html/wp-content/cache
2022-03-14 08:30:15 excluding directory public_html/wp-content/wp-cloudflare-super-page-cache
2022-03-14 08:30:15 excluding directory public_html/wp-content/updraft
2022-03-14 08:30:22 domain.com
2022-03-14 08:30:23 *** 5 domains ***

-- DNS --
2022-03-14 08:30:23 *** 0 domains ***

-- DB --
2022-03-14 08:30:23 user_domain_live (mysql)

Written: 0 MB   
                                                                               
/backup/tmp.80WiDVTRYR/db/user_domain_live/user_domain_live.mysql.sql :  6.64%   (43751656 => 2905468 bytes, /backup/tmp.80WiDVTRYR/db/user_domain_live/user_domain_live.mysql.sql.zst)
2022-03-14 08:30:25 user_domain_dev (mysql)

                                                                               
/backup/tmp.80WiDVTRYR/db/user_domain_dev/user_domain_dev.mysql.sql :  7.57%   (32472401 => 2458065 bytes, /backup/tmp.80WiDVTRYR/db/user_domain_dev/user_domain_dev.mysql.sql.zst)
2022-03-14 08:30:26 *** 2 databases ***

-- CRON --
2022-03-14 08:30:26 *** 2 jobs ***

-- User Dir --
2022-03-14 08:30:26 adding .bash_logout
2022-03-14 08:30:26 adding .bashrc
2022-03-14 08:30:26 adding .cache
2022-03-14 08:30:26 adding .composer
2022-03-14 08:30:26 adding .config
2022-03-14 08:30:26 adding .local
2022-03-14 08:30:26 adding .npm
2022-03-14 08:30:26 adding .profile
2022-03-14 08:30:26 adding .selected_editor
2022-03-14 08:30:26 adding .ssh
2022-03-14 08:30:26 adding .vscode-server
2022-03-14 08:30:26 adding .wp
2022-03-14 08:30:26 adding .wp-cli
2022-03-14 08:30:26 *** 13 directories ***

-- SUMMARY --
2022-03-14 08:30:28 Upload to B2: user/user.2022-03-14_08-30-26.tar
Error: b2 failed to upload user.2022-03-14_08-30-26.tar
```

**Comment by alx359** [comment]
Correlated but different bug. Regarding the cryptic B2 error message that got us into this issue. Recreated a new B2 `Application Key` and the B2 backup works okay now. The issue seems to do with a bad B2 authentication from `applicationKey` containing symbols that aren't `[a-zA-Z0-9]`. References [[1](https://forum.hestiacp.com/t/problems-configuring-remote-backup-with-b2-protocol-backblaze/5500)][[2](https://forum.hestiacp.com/t/error-b2-failed-to-upload-in-an-endless-job/5829/5)]

**Comment by jaapmarcus** [comment]
Change line:
https://github.com/hestiacp/hestiacp/blob/12b39f9435538a19923d53a00b757eea897a4d58/func/backup.sh#L438

to 

b2 authorize-account "$B2_KEYID" "$B2_KEY" > /dev/null 2>&1

And try again does it help

**Comment by alx359** [comment]
Have already deleted the `Application Key` giving me issues and can't seem to reproduce it anymore, even with another newly generated `applicationKey` that also contains a `+` sign. 

The backup to B2 is working fine now without the change you suggested. Perhaps in the meantime the issue got fixed in  `v1.5.11`?

Kindly note though the original issue described in this bug report is different, i.e. `Local backup = No` creates an endless loop when the B2 credentials get rejected.

Also bumped into another issue in  `v1.5.11`: 
`Backups > Remote backup > Application ID ` and `Application Key ` don't get updated in Hestia GUI, and one has to do it directly in `/usr/local/hestia/conf/b2.backup.conf`

**Comment by jaapmarcus** [comment]
https://forum.hestiacp.com/t/backblaze-application-key-not-save-correctly/6306

**Comment by ww7** [comment]
Annoying bug
It adds escaping slash for some symbols (like "+")

**Comment by ManuelReschke** [comment]
Not a solution for the bug but a good workaround:

- install rclone
- configure b2 storage [https://rclone.org/b2/](https://rclone.org/b2/)
- mount storage with rclone
- copy path from mount and set this folder as new backup folder in hestia:[https://docs.hestiacp.com/admin_docs/backups.html#how-to-change-default-backup-folder](https://docs.hestiacp.com/admin_docs/backups.html#how-to-change-default-backup-folder)

**Comment by ww7** [comment]
Still not fixed.
Please remove escaping. Script put wrong `\` inside B2_KEY if there a `+`

**Comment by ww7** [comment]
As temporal fix, check if in `/usr/local/hestia/conf/b2.backup.conf` correct keys.

**Comment by jaapmarcus** [comment]
Please try to changes in:
https://github.com/hestiacp/hestiacp/pull/2865/commits/f2c6c1bf3daee9ab65d6f4262b414f05f58c6f51#diff-d5f80b92a953a197e2e22744d09e81ca57d3bced48f51cbcd5c0ff81f63b8501L233

I am not able to test it as I am not able to generate a string containing an / or +

**Comment by ww7** [comment]
@jaapmarcus not working when "+" sign inside key string
this cause server not left space and server down with databases corruption

Log files show backup uploading stopped after update to 1.6.8 (with this fix)

**Comment by ww7** [comment]
Seems need some verification if key's correct, with some test upload

**Comment by jaapmarcus** [comment]
We should allready verify the account in:

```
    b2 clear-account > /dev/null 2>&1
    b2 authorize-account "$user" "$raw_password"> /dev/null 2>&1
    b2 ls --long "$host" "$user" > /dev/null 2>&1
```

Issue should be fixed

**Comment by ww7** [comment]
I think Hestia should cleanup `tmp` folders if backup uploading failed
If configuration broken (wrong keys or storage exceed/changed) Hestia create `tmp` folders until disk space is left.
It causes server down.

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/1e7998aac9671586aeda4a45a9cae0e303d50c5b/bin/v-backup-user#L712-L713

It is suppose to do that.
Maybe it doesn't work with b2 need to check it out imo

**Comment by ww7** [comment]
It doesn't work.
It seems exit from script if error
https://github.com/hestiacp/hestiacp/blob/9ef68d301d86d4bfe27e978911ff763aad1596eb/func/main.sh#L149-L162

Easy solution is a move ` # Removing tmpdir` higher `# Switching on backup system types`
https://github.com/hestiacp/hestiacp/blob/1e7998aac9671586aeda4a45a9cae0e303d50c5b/bin/v-backup-user#L701-L713
