### ISSUE TITLE
[Mail] Dovecot/Exim IP address assignment

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#263]
How to replicate:
1a.  Fresh installation of HESTIA.
1b.  Create new domain name (May be the same server's host name) + DNS + Email services.
2a. Create another domain with NAT/Floating IP

Issue:
1a. The DNS records got SMTP & IMAP records. But the server's mail service not using those records. Instead it uses the server's hostnames as SMTP/IMAP by default.
2a. If my domain is pointing to NAT IP, than the SMTP/IMAP also pointing to the same NAT but its wrong.

Question :
If by default those records are not in use, there is not need of those DNS records by default.

Kindly correct me, if my understanding is wrong.

**Comment by ghost** [comment]
Hello and thank you for your issue report. 

Issue 1a should be resolved in the next release, which features an updated mail subsystem. Mail headers should probably reflect mail.domain.tld in addition to supporting per domain SSL certificates. 

Can you please elaborate/clarify on the details for 2b and supply an example? Do you mean that the IP address supplied in the DNS records is incorrect or isn’t updated to reflect the NAT IP?

**Comment by vvcares** [comment]
Hi. Kris. Thank you for your superfast responses.
2b. I meant, the NAT IP is properly reflected. But the DNS records also IMAP-SMTP pointing to NAT ip. But All the domains under hestia, the exim/smtp/imap always pointing to the main IP. not depends on the NAT ip.

**Comment by ghost** [comment]
Thanks for clarifying, we will investigate further and report back when there's more information to share.

**Comment by ghost** [comment]
@vvcares, can you please test against the latest **develop** branch code by running the following commands and let us know if this behavior is still occurring?

```
wget https://raw.githubusercontent.com/hestiacp/hestiacp/develop/bin/v-update-sys-hestia-git
chmod +x v-update-sys-hestia-git && mv v-update-sys-hestia-git $HESTIA/bin
v-update-sys-hestia-git develop
```

Normally you would only need to run `v-update-sys-hestia-git`, however there is a bug in the latest release which prevents it from working correctly.

**Comment by vvcares** [comment]
Hi,
I upgraded as above [1.00.0-190618].
Seems the issue still persists as..
1. If I created a domain with public ip 1.1.1.1 > IMAP/SMTP pointing to 1.1.1.1
2. If i created a domain with NAT ip 2.2.2.2 > IMAP/SMTP poointing to 2.2.2.2

This is not correct. It still should point to my server's public IP only (1.1.1.1).
But wonder, my webmail A record pointing to 1.1.1.1.. :-)

**Comment by vvcares** [comment]
Hi team. So whats the final decision.?
Just curious to know your valuable changes..
