### ISSUE TITLE
Default website domain for unknown hosts pointing to server

### ISSUE THREAD

**Issue by vvcares** [hestiacp/hestiacp#328]
Default website domain for unknown hosts pointing to server:

REQUEST ; Need to set a default domain-error page for unknown/orphaned hostnames pointing to HESTIA server ip as 'A' record, but there no such hostname inside hestia. (same like cPanel etc.,)

ISSUE : The server shows the latest created website domain for unknown/orphaned hostnames

HOW TO REPLICATE : Just create a 'dummy.com' on your external DNS manager (out of HESTIA). Normally on your domain register page, DNS settings. Point the 'dummy.com' A-record point to your HESTIA server web ip. But dont create such hostname 'dummy.com' inside HESTIA. Now try to access that 'dummy.com' via browser. It will resolve to the existing latest hestia's domain as website.

ISSUE : 
1. If i have some login form links, it may fail (due to the form sending data to different domain) & same time it will sends the wrong userid/password details to that wrong domain's apache logs.

2. The google index will crawl the wrong domains contents & marked as duplicated content and SEO Penalty

3. Professional image spoilt when real customer visited to the intended domain but showing different domain.

Ref: https://forum.vestacp.com/viewtopic.php?t=14070

**Comment by Lupul** [comment]
Can you check the develop branch? it was fixed there a couple of weeks ago.

https://github.com/hestiacp/hestiacp/commits/e42670c878d1f3e952f1944e22cfe52bd68e951a/install/deb/apache2/unassigned.conf

**Comment by vvcares** [comment]
hi,
how to implement this?

What i did?
- i created new file '/etc/apache2/unassigned.conf'
- Placed the contents as 

```
<VirtualHost MyPublicIpxx.xx.xx.xx:80>
    ServerName MyPublicIpxx.xx.xx.xx
    DocumentRoot /var/www/html/
    Alias /error/ /var/www/document_errors/

</VirtualHost>

<VirtualHost MyPublicIpxx.xx.xx.xx:443>
    ServerName MyPublicIpxx.xx.xx.xx
    DocumentRoot /var/www/html/
    Alias /error/ /var/www/document_errors/

    SSLEngine on
    SSLVerifyClient none
    SSLCertificateFile         /usr/local/hestia/ssl/certificate.crt
    SSLCertificateKeyFile      /usr/local/hestia/ssl/certificate.key
</VirtualHost>
```

- Restarted the APACHE2 & NGINX
- On my cloudflare > created new DNS-A record pointing to 'MyPublicIpxx.xx.xx.xx'
- Still seeing another domain's page

**Comment by ScIT-Raphael** [comment]
I would suggest to wait for the new release instead do a partital implementation based on some commits. Release is planed in around 1 or 2 weeks, based on how much additional bugs we will find :).
