### ISSUE TITLE
[bug] Errors accessing phppgadmin 

### ISSUE THREAD

**Issue by mach0** [hestiacp/hestiacp#872]
### In a few words, please describe the issue that you're experiencing:
error accessing phppgadmin.
Installed the upcoming hestiacp 1.2.0 but that also did not change the issue:
Accessing https://domainname/phppgadmin gives:
Configuration error: Copy conf/config.inc.php-dist to conf/config.inc.php and edit appropriately.
plus further error after trying to fix - see down below
 
### What steps did you take when the issue occured? 
1. Ex.: Log into the Hestia Control Panel using Firefox and Chrome
2. Ex.: go to an existing domain on the server and try to access the phppgadmin panel

### Expected behavior:
Access to phppgadmin allowed and functional

### Does this issue always occur, or is it intermittent?
always

### Operating system distribution and release:
debian 10 buster

### Which version of Hestia Control Panel is currently installed?
1.2.0

### Which branch are you using?
prepared 1.2.0 deb from the forum (installed 22.6.2020)

### When did this issue occur? After a clean installation, or after an upgrade?
from the beginning with 1.1.2 also after upgrade 1.2.0

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP
- PHP-FPM + Multi-PHP

### In order to better assist, please post any relevant log information below:
First:
Configuration error: Copy conf/config.inc.php-dist to conf/config.inc.php and edit appropriately.
(seems that access to the config file the link points to is not allowed)
After directly copying the config.inc.php from /etc/phppgadmin/config.inc.php to /usr/share/phppgadmin/conf the error is:
Your PHP installation does not support PostgreSQL. You need to recompile PHP using the --with-pgsql configure option.

### Related issues or forum threads:
Did not find any relevant info in issues or forum (wonder how people access phppgadmin :) )

### Additional notes:
My guess is that first the path to /etc/phppgadmin should be added to the php template like:
/usr/local/hestia/install/deb/templates/web/php-fpm/default.tpl

php_admin_value[open_basedir] = /home/%user%/web/%domain%/public_html:/home/%user%/web/%domain%/public_shtml:/home/%user%/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:/etc/phppgadmin:/etc/roundcube:/var/lib/roundcube:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt

second: compile PHP with --with-pgsql

**Comment by jaapmarcus** [comment]
1.1.2 was never released was it not 1.1.1?

Just did some testing

https://my.domain.tld/phppgadmin/ doesn't work same error as you

https://123.123.123.123/phppgadmin/ works with out a issue...

We need to have look into it.

**Comment by mach0** [comment]
hi and thanks for your answer.

at first I tested release 1.1.1 and afterwards upgraded to 1.2.0 with this forum link:
https://forum.hestiacp.com/t/hestia-1-2-0-rc-we-need-you/1061

never tried using the IP address, but thanks for the hint.
If I can help in any way just drop me a note.

**Comment by jaapmarcus** [comment]
We will probably add the /etc/phppgadmin/:/usr/share/phppgadmin to all the php-fpm templates and this will solve the issue.

For the second error are you using a different php version then the 7.3?  With 7.3 I have no issue...

**Comment by mach0** [comment]
since using the IP address I cannot reproduce the error with no psql support in php version.
Hope this was just a problem resulting from using the domainname.

**Comment by jaapmarcus** [comment]
Did you use multiphp flag during installation?

**Comment by mach0** [comment]
yes I did, and I also deleted the php versions which are not supported upstream in php anymore

**Comment by jaapmarcus** [comment]
There could be some issues then thank you any way :)

**Comment by jaapmarcus** [comment]
The https://domain.com/phppgadmin/ should be fixed when 1.2.0 is released. We still need to look into what is going wrong with Debian and Multpi PHP install

How ever the easiest why to solve is to use --phpfpm yes  and do it with in the web interface as this will also allow you to select less versions (Only the versions you would need/want)

**Comment by mach0** [comment]
thx for the fix.
do you mean I should try reinstalling without "multiphp" but rather phpfpm?
close the issue or leave it open unless tested?

**Comment by ScIT-Raphael** [comment]
MultiPHP flag isnt needed since release 1.1.0, you can now add and remove php versions like you want - the multiphp flag just installs every version from 5.6 to 7.4 - which mostly isnt needed at all :). So if you like, you could give it a try without the multiphp flag.

**Comment by mach0** [comment]
thx a lot - will reinstall as soon as I find some time for it. If you need me something to test - I'll gladly help.

**Comment by ghost** [comment]
@mach0, have you been able to confirm that this issue is resolved? Please install v1.2.0 release candidate 2 and let us know:

**Download:** `wget https://apt.hestiacp.com/beta/hestia_1.2.0_amd64.deb`
**Install:** `dpkg -i hestia_1.2.0_amd64.deb`

**Comment by mach0** [comment]
sorry for the late reply, was changing jobs.
just installed it and IP/phppgadmin is still working while
domainname/phppgadmin does not..
Is a restart mandatory?
Is an active postgres database inside the domain mandatory?

The Message is still:
Configuration error: Copy conf/config.inc.php-dist to conf/config.inc.php and edit appropriately.

**Comment by ghost** [comment]
Can you please run `v-update-sys-hestia-git master yes` on the server to bring it up to date with the latest changes for 1.2.0 to see if the issue is now corrected?

**Comment by mach0** [comment]
just fired the command - no changes when using domain/subdomain (pointing to IP-address) and */phppgadmin 
but it still works with IP-Address/phppgadmin ..

**Comment by jaapmarcus** [comment]
Could you give me the output of the command?

And what php version are you using for the domain?

**Comment by mach0** [comment]
@jaapmarcus
you mean the output of the 
`v-update-sys-hestia-git master yes`
command?
Or the output of calling domainname/phppgadmin ?

**Comment by jaapmarcus** [comment]
Output of calling 

v-update-sys-hestia-git master yes

**Comment by mach0** [comment]
boah - that was quite long including installation of the newly created debian package.
But I could not see any error inside if you mean that.
As it is already installed I can call the line again and paste the output here if you want.

**Comment by mach0** [comment]
luckily found it in the shell backlog:

:~# v-update-sys-hestia-git master yes
Changed release branch to master.
Updating system APT repositories...
Installing dependencies for compilation...
Building Hestia Control Panel package...
master.tar.gz           [          <=>       ]   3.19M  1.55MB/s    in 2.1s    
control             100%[===================>]     514  --.-KB/s    in 0s      
copyright           100%[===================>]   1.35K  --.-KB/s    in 0s      
postinst            100%[===================>]   1.52K  --.-KB/s    in 0s      
dpkg-deb: building package 'hestia' in 'hestia_1.2.0_amd64.deb'.
Installing packages...
(Reading database ... 87364 files and directories currently installed.)
Preparing to unpack ...//debs//hestia_1.2.0_amd64.deb ...
Unpacking hestia (1.2.0) over (1.2.0) ...
Setting up hestia (1.2.0) ...

                _   _           _   _        ____ ____                  
               | | | | ___  ___| |_(_) __ _ / ___|  _ \                 
               | |_| |/ _ \/ __| __| |/ _` | |   | |_) |                
               |  _  |  __/\__ \ |_| | (_| | |___|  __/                 
               |_| |_|\___||___/\__|_|\__,_|\____|_|                    
                                                                        
                  Hestia Control Panel Software Update                  
                            Version: 1.2.0                       
========================================================================

(!) IMPORTANT INFORMATION:                                              

Default configuration files and templates may be modified or replaced   
during the upgrade process. You may restore these files from:           

Backup directory: /root/hst_backups/060720201129/                                       

This process may take a few minutes, please wait...                     

========================================================================

(!) The latest version of Hestia Control Panel is already installed.
    Verifying configuration...

(*) Updating Roundcube configuration...
(*) Updating exim4 configuration...
(*) Updating Apache2 configuration...
(*) Updating File Manager configuration...
(*) Updating NGINX configuration...
(*) Updating public_(s)html ownership...
(*) Updating phpMyAdmin permissions...
(*) Updating default templates for PHP 7.3...
(*) Updating default templates for PHP 7.4...
(*) Rebuilding domains and account for user: admin...
(*) Rebuilding domains and account for user: wmacho...
(*) Rebuilding domains and account for user: gisdb...
(*) Applying user interface updates...
(*) Restarting services...

========================================================================

Upgrade complete! If you encounter any issues or find a bug,            
please take a moment to report it to us on GitHub at the URL below:     
https://github.com/hestiacp/hestiacp/issues                             

We hope that you enjoy using this version of Hestia Control Panel,      
have a wonderful day!                                                   

Sincerely,                                                              
The Hestia Control Panel development team                               

Web:      https://www.hestiacp.com/                                     
Forum:    https://forum.hestiacp.com/                                   
GitHub:   https://github.com/hestiacp/hestiacp/                        
E-mail:   info@hestiacp.com                                             

Made with love & pride by the open-source community around the world.

**Comment by jaapmarcus** [comment]
Hmm it should apply the command

What PHP FPM template is currently used?

**Comment by mach0** [comment]
it looks like php-7.3 is default but honestly I am not sure.
Howto find out which is default?
I installed and used php-7.4 on a testdomain

**Comment by jaapmarcus** [comment]
Go to /list/web/ Click on you domain and then Backend Template PHP-FPM

If you are seeing PHP-7_3 where the part behind the - is the version

**Comment by mach0** [comment]
Backend Template 
default

So where can I see which is default?

**Comment by jaapmarcus** [comment]
Please check /usr/local/hestia/data/template/php-fpm/default.tpl 

Line 20 should contain that value
php_admin_value[open_basedir] = /home/%user%/web/%domain%/public_html:/home/%user%/web/%domain%/public_shtml:/home/%user%/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:**/etc/phppgadmin**:/etc/roundcube:/var/lib/roundcube:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt

If not we need to check why the template is not overwritten during install

**Comment by mach0** [comment]
panel:/usr/local/hestia/data$ ls
firewall  ips  packages  queue  sessions  templates  users
panel:/usr/local/hestia/data$ cd templates/
panel:/usr/local/hestia/data/templates$ ls
dns  mail  themes  web
panel:/usr/local/hestia/data/templates$ 

there is no templatE directory - and therefor no php-fpm dir ..

**Comment by jaapmarcus** [comment]
Sorry it is  /usr/local/hestia/data/templates/web/php-fpm/default.tpl

**Comment by mach0** [comment]
thx - but unfortunately phppgadmin is still missing there:
php_admin_value[open_basedir] = /home/%user%/web/%domain%/public_html:/home/%user%/web/%domain%/public_shtml:/home/%user%/tmp:/var/www/html:/etc/phpmyadmin:/var/lib/phpmyadmin:/etc/roundcube:/var/lib/roundcube:/
I can add it manuall now, but that would mean it's still not in the package..
Any hints what could have gone wrong?
The Webpage tells me I'm on 1.2.0 - so that is ok so far

**Comment by ghost** [comment]
This should now be resolved, can you run `v-update-sys-hestia-git master yes` on your server and check the results for phpPgAdmin please?

**Comment by mach0** [comment]
Hi! Just updated and it is working now with the domainname too.
Thanks a lot. issue can be closed.

**Comment by mach0** [comment]
reopening this issue due to the same error reappearing with the release of 1.4.6

**Comment by jaapmarcus** [comment]
Probally because www conf is not loaded. In apache2..

Add 
https://github.com/hestiacp/hestiacp/blob/bca0496c5f80a3c3642fc97993532c695be55f0a/install/deb/pma/apache.conf#L20-L25

Just below:
https://github.com/hestiacp/hestiacp/blob/bca0496c5f80a3c3642fc97993532c695be55f0a/install/deb/pga/phppgadmin.conf#L13-L17

in /etc/apache2/conf.d/phpgadmin/

**Comment by vdbhb59** [comment]
I tried everything, but does not solve this same issue with my instance.
I get incorrect repository provided when running the master yes.
Moreover, my PHP8.2 has vanished from the list of monitoring page.
Any help please?

**Comment by ScIT-Raphael** [comment]
We do not provide any support over github, please switch to forum.hestiacp.com.
